### ISSUE TITLE
Aufgabe 4

### ISSUE THREAD

**Issue by Plagiatus** [ulmschnp/GIS-SoSe-20#2]
Ampel:
- Errors in W3.

Sonstiges:
- Wenn du Code kopierst, dann machst du was falsch und es gibt (fast) immer eine bessere Lösung. In diesem Fall wäre es besser alles, was für eine Seitengröße gilt, als "Standard" festzusetzen und dann in den Media Queries nur das zu überschreiben, was sich ändert.
- Warum verändert sich die Reihenfolge/Anordnung vom Hauptmenü?
- was ändert sich überhaupt bei 600 px (bzw 700 weil du den falschen Wert genommen hast)?
- wirklich schön isses ja nicht, und das mit Margins auf den Artikeln auch nicht.

du stehst jetzt zwar auf Rot, aber das kannst du im Praktikum nochmal auf gelb-rot zurück verteidigen, noch bist du also nicht durchgefallen.

**Comment by ulmschnp** [comment]
guten Morgen,
habe die Aufgabe verbessert, dh alle w3 Errors behoben und die Seite passt sich jetzt Automatisch der Bildschiormgröße an, da ich jetzt alles prozentdual laufen hab.
Hoffe es reicht für noch eine chance des praktikum zu bestehen, ich weiß ist nicht die hübscheste Web-site, aber werde sie was optik betrifft im laufe der woche noch bearbeiten(schönheit liegt immer im Sinne des Betrachters ^^). Würde mich sehr auf eine letzte chance freuen, da html etc mich schon intressiert, es nur meist auf der strecke liegen blieb durch andere abgaben und ich ziemlich oft durcheinader gekommen bin mit prog1.
mfg Patrick
Am Montag, Mai 25, 2020 14:22 CEST, schrieb Lukas Scheuerle <notifications@github.com>:
 
 
Ampel:
 * Errors in W3.
Sonstiges:
 * Wenn du Code kopierst, dann machst du was falsch und es gibt (fast) immer eine bessere Lösung. In diesem Fall wäre es besser alles, was für eine Seitengröße gilt, als "Standard" festzusetzen und dann in den Media Queries nur das zu überschreiben, was sich ändert. * Warum verändert sich die Reihenfolge/Anordnung vom Hauptmenü? * was ändert sich überhaupt bei 600 px (bzw 700 weil du den falschen Wert genommen hast)? * wirklich schön isses ja nicht, und das mit Margins auf den Artikeln auch nicht.
du stehst jetzt zwar auf Rot, aber das kannst du im Praktikum nochmal auf gelb-rot zurück verteidigen, noch bist du also nicht durchgefallen.

**Comment by Plagiatus** [comment]
Verteidigung ist wie immer persönlich im Praktikum, da können wir dann gerne zusammen über deine Änderungen und Verbesserungen reden. 😃

**Comment by ulmschnp** [comment]
gerne wie komme ich denn auf dieses online portal? finde nirgends den link dazu^^
Am Mittwoch, Mai 27, 2020 09:42 CEST, schrieb Lukas Scheuerle <notifications@github.com>:
 
 
Verteidigung ist wie immer persönlich im Praktikum, da können wir dann gerne zusammen über deine Änderungen und Verbesserungen reden. 😃
